version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - chmod +x export_container_and_upload
      - ./export_container_and_upload
artifacts:
  files:
    - 'microservice.tar'