#!/usr/bin/env bash

docker build -t microservice .
docker run -d --name microservice -p 8080:8080 microservice
docker export microservice > microservicecontainer.tar
docker save microservice > microserviceimage.tar
