#!/usr/bin/env bash


#Use case is the same as git push with a commit message



//Squash
git rebase -i HEAD~[NUMBER OF COMMITS]

OR

git rebase -i [SHA]

If you have previously pushed your code to a remote branch, you will need to force push.

git push origin branchName --force

Checkout master branch

git checkout master

Pull master branch

git pull origin master

Checkout bug/feature branch

git checkout branchName

Rebase from master

git rebase master

Handle any conflicts and make sure your code builds and all tests pass. Force push branch to remote.

git push origin branchName --force

Checkout, merge, and push into master

git checkout master

git merge branchName

git push origin master

#Check if a pull request already exists

#if it does bail out

# if it doesn't: Create Pull Request
curl --data '{"title":"newBranch","base":"master","head":"newBranch","body":"Please merge this"}' -X POST -H "Authorization: token {token}" https://api.github.com/repos/ogdenm/microService/pulls

#if the pull request successed
